#!/usr/bin/env sh
set -e

PRETTIER_FILES="$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')"
if [ -n "$PRETTIER_FILES" ]; then
	pnpm exec prettier $PRETTIER_FILES --write --ignore-unknown
	git update-index --again
fi

pnpm lint
